# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-03 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_friend', to='first_app.User')),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_user', to='first_app.User')),
            ],
        ),
    ]
