# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-04 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_remove_user_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='user_2',
            new_name='second_friend',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='user_1',
            new_name='user_friend',
        ),
    ]
