# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-04 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20180404_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='user_friend',
            new_name='added_user',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='second_friend',
            new_name='main_user',
        ),
    ]
